### ISSUE TITLE
可以添加允许代理的功能吗

### ISSUE THREAD

**Issue by R1kka0612** [Coolapk-UWP/Coolapk-UWP#108]
当前版本开启代理后无法联网，能不能添加选项是否走代理，类似网易云那种

**Comment by wherewhere** [comment]
不好(不会<img alt="流汗滑稽" src="https://raw.fastgit.org/Tangent-90/Coolapk-UWP/master/src/CoolapkUWP/Assets/Emoji/1259.png" width="20px" />

**Comment by lancerXXXX** [comment]
> 当前版本开启代理后无法联网，能不能添加选项是否走代理，类似网易云那种

![image](https://user-images.githubusercontent.com/42160297/123545134-223f5780-d789-11eb-8bfc-cec259b9e7d0.png)

这里设置-》就可以了

**Comment by fange173** [comment]
> > 当前版本开启代理后无法联网，能不能添加选项是否走代理，类似网易云那种
> 
> ![image](https://user-images.githubusercontent.com/42160297/123545134-223f5780-d789-11eb-8bfc-cec259b9e7d0.png)
> 
> 这里设置-》就可以了

谢谢 可以用了

**Comment by onionycs** [comment]
果然有人已经问过这个问题了
![图片](https://user-images.githubusercontent.com/37523020/145157474-cf89b184-6139-45e1-80c5-af60e9c1a76f.png)
