### ISSUE TITLE
搜索框内输入"win11 "稳定报错

### ISSUE THREAD

**Issue by subframe7536** [Coolapk-UWP/Coolapk-UWP#123]
![image](https://user-images.githubusercontent.com/78338239/135782002-ae9775fa-6406-4223-b43a-ff0b2135e5dc.png)
其他的没试出来
- 最好应用内可以反馈，或者说我没找到？

**Comment by subframe7536** [comment]
不过只是报错，功能可以正常使用

**Comment by subframe7536** [comment]
![image](https://user-images.githubusercontent.com/78338239/135782363-133dad8c-eefd-492a-ac03-b64d54e9e017.png)
还有使用搜狗输入法的时候候选框会被遮挡

**Comment by subframe7536** [comment]
找到了[Log - 20211004.log](https://github.com/Coolapk-UWP/Coolapk-UWP/files/7275043/Log.-.20211004.log)

**Comment by wherewhere** [comment]
> ![image](https://user-images.githubusercontent.com/78338239/135782363-133dad8c-eefd-492a-ac03-b64d54e9e017.png)
> 还有使用搜狗输入法的时候候选框会被遮挡

这个是输入法不兼容，应该无解
