### ISSUE TITLE
求助！开发人员证书已到期！

### ISSUE THREAD

**Issue by SKT-TheShy** [Coolapk-UWP/Coolapk-UWP#126]
右键install.ps1使用PowerShell运行，显示 “开发人员证书已到期。一个可能的原因是系统时钟未设置为正确的日期和时间。如果系统设置正确，请与应用程序所有者联系以使用有效的证书重新创建包或捆绑。” ，请问这个如何操作？
![Uploading image.png…]()

**Comment by wherewhere** [comment]
【UWP】手把手教你回到过去安装签名过期的UWP https://b23.tv/KvqZxU

**Comment by SKT-TheShy** [comment]
Thinks！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Coolapk-UWP/Coolapk-UWP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月11日(星期一) 中午12:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Coolapk-UWP/Coolapk-UWP] 求助！开发人员证书已到期！ (#126)





 
【UWP】手把手教你回到过去安装签名过期的UWP https://b23.tv/KvqZxU
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
