### ISSUE TITLE
安装好后显示网络异常

### ISSUE THREAD

**Issue by Meteorsss** [Coolapk-UWP/Coolapk-UWP#130]
安装好后显示网络异常咋办啊？

**Comment by wherewhere** [comment]
去设置把权限打开

**Comment by wherewhere** [comment]
[![轻松解决 Surface 上 UWP 无法联网的问题](https://user-images.githubusercontent.com/27689196/145774945-0022d6f9-f838-450b-a9dc-a19eb6159434.png)](https://b23.tv/iDSJqg4)
