### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by SiMaLaoShi** [Coolapk-UWP/Coolapk-UWP#133]
选任何一个话题，然后按时间啊排序
![image](https://user-images.githubusercontent.com/28924681/150294405-afbefcd4-c1af-4eac-8914-5f386ce0de17.png)
![image](https://user-images.githubusercontent.com/28924681/150294420-8b86cc96-e762-4c0f-94f6-fde99e084903.png)
而且部分话题只能刷一点点内容出来

**Comment by wherewhere** [comment]
不想维护了。。。
等一个接盘的人<img alt="幽灵" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" />

**Comment by wherewhere** [comment]
换坑之后应该没有这个问题了
