### ISSUE TITLE
小图要点两遍才显示

### ISSUE THREAD

**Issue by Geekiter** [Coolapk-UWP/Coolapk-UWP#140]
80%出现，小图点开，不显示。

- 要么重新点开小图，那么帖子里所有图片都能看。
- 要么点查看原图，帖子里每个图片都有点查看原图才能看。

另外，反馈一个，头条浏览到最后一条时，有一定几率卡在最后一条，即使后面的分页数据已经获取到了，我往下滚动，又自动弹回来了。

**Comment by wherewhere** [comment]
不再维护，这个屎山太烂了。。。
