### ISSUE TITLE
运行ps1脚本报错

### ISSUE THREAD

**Issue by yhm2046** [Coolapk-UWP/Coolapk-UWP#141]
windows7直接闪退

windows10提示:找到了捆绑: C:\Users\Adan0\Downloads\CoolapkUWP_2.1.38.0_Test\CoolapkUWP_2.1.38.0_x86_x64_arm_arm64.appxbundle
找到证书: C:\Users\Adan0\Downloads\CoolapkUWP_2.1.38.0_Test\CoolapkUWP_2.1.38.0_x86_x64_arm_arm64.cer
错误: 开发人员证书“C:\Users\Adan0\Downloads\CoolapkUWP_2.1.38.0_Test\CoolapkUWP_2.1.38.0_x86_x64_arm_arm64.cer”已到期 。一个可能的原因是系统时钟未设置为正确的日期和时间。如果系统设置正确，请与应用程序所有者联系以使用有效的证书重新创建包或捆绑。
按 Enter 键继续...:

**Comment by wherewhere** [comment]
神奇，UWP不支持不支持UWP的平台

**Comment by yhm2046** [comment]
还没有老铁解决吗？可付费

**Comment by wherewhere** [comment]
好啊，你给钱我就教你/滑稽

**Comment by amlkiller** [comment]
似乎改系统时间能解决

**Comment by amlkiller** [comment]
> 

这不行

**Comment by yhm2046** [comment]
> 

多少钱？

**Comment by wherewhere** [comment]
坏诶，算了，你先说一下你的系统配置吧

**Comment by yhm2046** [comment]
> 坏诶，算了，你先说一下你的系统配置吧

win10，win7 64bit系统我都试过了都不行

**Comment by wherewhere** [comment]
请具体一点，版本号，发行分支

**Comment by wherewhere** [comment]
> > 请具体一点，版本号，发行分支
> 
> 仔细试过了，就是你开发人员证书又过期了。
> 现在的可以把系统时间改到证书有效期内，
> 比如20年十月份，右键cer证书看有效期改进里面。

不更新证书，不接受更新证书请求，不回答有关证书过期的问题

**Comment by wherewhere** [comment]
> Windows 10 专业版  19044.1706, 这是家里台式，公司的要明天上班才能发
> 

你先尝试按照这个教程安装
[【UWP】手把手教你“回到过去”安装签名过期的UWP-哔哩哔哩] (https://b23.tv/HtwWpNl)

**Comment by wherewhere** [comment]
> > > > 请具体一点，版本号，发行分支
> > > 
> > > 
> > > 仔细试过了，就是你开发人员证书又过期了。
> > > 现在的可以把系统时间改到证书有效期内，
> > > 比如20年十月份，右键cer证书看有效期改进里面。
> > 
> > 不更新证书，不接受更新证书请求，不回答有关证书过期的问题
> 
> 既然这样，不如解决一下bug，比如第一次打开加载的图片，图片渲染不正常，要重新打开。

不再进行任何更新，不再接受任何提议，有需求请自行提交Commit

**Comment by yhm2046** [comment]
> > Windows 10 专业版  19044.1706, 这是家里台式，公司的要明天上班才能发
> 
> 你先尝试按照这个教程安装 [【UWP】手把手教你“回到过去”安装签名过期的UWP-哔哩哔哩](https://b23.tv/HtwWpNl)

谢谢，我先研究一下，刚刚才发现原来你是作者 ：)
