### ISSUE TITLE
v2.1.38安装时证书过期导致无法安装

### ISSUE THREAD

**Issue by mayjack0312** [Coolapk-UWP/Coolapk-UWP#143]
- 安装版本：v2.1.38
- 安装时间：2022年6月25日
- 提示信息：无法验证此应用包的发布者证书。请与系统管理员或应用开发人员联系，以获取具有验证证书的新应用包。必须验证应用包中签名的根证书和所有直接证书(0x800B010A)

**Comment by nagisastudio** [comment]
把系统时间调到2021年就可以，安装好后调回来，证书也要添加到本机信任。

**Comment by mayjack0312** [comment]
> 把系统时间调到2021年就可以，安装好后调回来，证书也要添加到本机信任。

好的，谢谢您啦

**Comment by Administrator6wyj** [comment]
学会了

**Comment by k650dg4d2** [comment]
> 把系统时间调到2021年就可以，安装好后调回来，证书也要添加到本机信任。

还是不能安装

**Comment by win98se** [comment]
> > 把系统时间调到2021年就可以，安装好后调回来，证书也要添加到本机信任。
> 
> 还是不能安装 ![QQ截图20200905203830](https://user-images.githubusercontent.com/32454224/188451603-19eb7211-cd7f-46bc-9683-f85782ab7790.png)

查看证书日期，是从2020年10月9日开始的，试试看
