### ISSUE TITLE
网络链接错误

### ISSUE THREAD

**Issue by conquer1the2world3** [Coolapk-UWP/Coolapk-UWP#149]
### Describe the bug

打开软件就显示网络异常，是只有我一个人有问题吗

### Steps to reproduce the bug

打开软件

### Screenshots

![image](https://user-images.githubusercontent.com/63401784/187119649-cf46030f-14f5-4ad9-acd8-fd5570876cbd.png)
![image](https://user-images.githubusercontent.com/63401784/187119571-5c4fff8a-457a-4d3a-9bd7-17f8ee3e2c16.png)

### App version

2.1.39

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### Device

Desktop

**Comment by wherewhere** [comment]
在浏览器中输入 coolapk://flags ，然后修改API版本，如果还不能用就卸载吧，当作这个东西从来也没有存在过

**Comment by Mr-SPM** [comment]
这么狠吗？直接就当没存在过？

**Comment by wherewhere** [comment]
https://dev.azure.com/wherewhere/Coolapk-UWP/_build/latest?definitionId=2&branchName=master
如果还是不行我也没办法了(我这边能用

**Comment by q123458384** [comment]
> https://dev.azure.com/wherewhere/Coolapk-UWP/_build/latest?definitionId=2&branchName=master 如果还是不行我也没办法了(我这边能用

输入`coolapk://flags`直接转跳程序，没有修改版API版本的选项？
8月30日更新的那个安装提示：
```
Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073CFB, 提供的程序包已安装，且禁止重新安装该程序包。请检查 AppXDeployme
nt-Server 事件日志了解详细信息。

已阻止程序包 Tangent90.CoolapkUWP_2.1.38.0_neutral_split.scale-150_d0s2e6z6qkbn0 的部署，因为提供的程序包具有与已安装的
程序包相同的标识，但内容不相同。请提高要安装的程序包的版本号，或者删除系统上的每个用户的旧程序包，然后再安装此程序包。
```
不知道怎么卸载

**Comment by q123458384** [comment]
用这个命令卸载了旧版：`Get-AppxPackage *Coolapk* | remove-appxpackage`
然后重新安装作者上面提供的8.30版本可以正常联网了

**Comment by zhuangside** [comment]
> 

请问在哪里输入这行命令

**Comment by zhuangside** [comment]
> 用这个命令卸载了旧版： 然后重新安装作者上面提供的8.30版本可以正常联网了`Get-AppxPackage *Coolapk* | remove-appxpackage`

请问在哪里输入这行命令

**Comment by q123458384** [comment]
> > 用这个命令卸载了旧版： 然后重新安装作者上面提供的8.30版本可以正常联网了`Get-AppxPackage *Coolapk* | remove-appxpackage`
> 
> 请问在哪里输入这行命令

powershell

**Comment by wherewhere** [comment]
最新版已经更换接口，可以使用了。。。

**Comment by Yzzzed** [comment]
> 用这个命令卸载了旧版：`Get-AppxPackage *Coolapk* | remove-appxpackage` 然后重新安装作者上面提供的8.30版本可以正常联网了

请问下卸载了如何安装最新的 需要自己编译吗 releases还是21年的

**Comment by q123458384** [comment]
> > 用这个命令卸载了旧版：`Get-AppxPackage *Coolapk* | remove-appxpackage` 然后重新安装作者上面提供的8.30版本可以正常联网了
> 
> 请问下卸载了如何安装最新的 需要自己编译吗 releases还是21年的

求上面作者发的链接啊
然后点击`1published` 点击drop下载
https://dev.azure.com/wherewhere/Coolapk-UWP/_build/results?buildId=447&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by Administrator6wyj** [comment]
> 

跟着你的操作，一步步下来，成功解决问题，感谢分享！

**Comment by searlas** [comment]
不知道是不是只有我这样，打开最新版的详情页就程序出现错误

**Comment by Yzzzed** [comment]
> 不知道是不是只有我这样，打开最新版的详情页就程序出现错误

我也是 程序出现错误

**Comment by searlas** [comment]
> 不知道是不是只有我这样，打开最新版的详情页就程序出现错误

我又莫名其妙好了。。。

**Comment by wherewhere** [comment]
出现网络问题一般是都是酷安的锅，问我我也没法解决

**Comment by WrathGluttony** [comment]
> 用这个命令卸载了旧版：`Get-AppxPackage *Coolapk* | remove-appxpackage` 然后重新安装作者上面提供的8.30版本可以正常联网了

作者上面提供的8.30版本下载下来安装后，版本号也是2.1.38.0，这和01 May 2021发布的release版本号(2.1.38)是一样的，楼主的版本号是2.1.39，请问应该下载哪个版本？

**Comment by wherewhere** [comment]
只要你喜欢，版本号随便改

**Comment by WrathGluttony** [comment]
> 只要你喜欢，版本号随便改

谢谢大神，能添加对MacType的支持吗？就是Win10下字体的渲染

**Comment by wherewhere** [comment]
不能，你自己装字体不就行了

**Comment by WrathGluttony** [comment]
> 不能，你自己装字体不就行了

好的，多谢

**Comment by Guciliang** [comment]
> ### Describe the bug
> 打开软件就显示网络异常，是只有我一个人有问题吗
> 
> ### Steps to reproduce the bug
> 打开软件
> 
> ### Expected behavior
> _No response_
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/63401784/187119649-cf46030f-14f5-4ad9-acd8-fd5570876cbd.png) ![image](https://user-images.githubusercontent.com/63401784/187119571-5c4fff8a-457a-4d3a-9bd7-17f8ee3e2c16.png)
> 
> ### App version
> 2.1.39
> 
> ### Windows version
> Windows 10 version 21H2 (19044, November 2021 Update)
> 
> ### Device
> Desktop
> 
> ### Additional context
> _No response_
卸载后安装成功了

**Comment by Guciliang** [comment]
> 用这个命令卸载了旧版：`Get-AppxPackage *Coolapk* | remove-appxpackage` 然后重新安装作者上面提供的8.30版本可以正常联网了

谢谢

**Comment by Qianchang08** [comment]
> > > 用这个命令卸载了旧版：`Get-AppxPackage *Coolapk* | remove-appxpackage` 然后重新安装作者上面提供的8.30版本可以正常联网了
> > 
> > 
> > 请问下卸载了如何安装最新的 需要自己编译吗 releases还是21年的
> 
> 求上面作者发的链接啊 然后点击`1published` 点击drop下载 https://dev.azure.com/wherewhere/Coolapk-UWP/_build/results?buildId=447&view=artifacts&pathAsName=false&type=publishedArtifacts

感谢感谢，牛逼，真的能用了

**Comment by ysnklt** [comment]
> > > 用这个命令卸载了旧版：`Get-AppxPackage *Coolapk* | remove-appxpackage` 然后重新安装作者上面提供的8.30版本可以正常联网了
> > 
> > 
> > 请问下卸载了如何安装最新的 需要自己编译吗 releases还是21年的
> 
> 求上面作者发的链接啊 然后点击`1published` 点击drop下载 https://dev.azure.com/wherewhere/Coolapk-UWP/_build/results?buildId=447&view=artifacts&pathAsName=false&type=publishedArtifacts

这个链接是不是失效了 没看到包

**Comment by Qianchang08** [comment]
好像是的，我有文件，需要可以发给你



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月1日(周六) 晚上6:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Coolapk-UWP/Coolapk-UWP] 网络链接错误 (Issue #149)




    
用这个命令卸载了旧版：Get-AppxPackage *Coolapk* | remove-appxpackage 然后重新安装作者上面提供的8.30版本可以正常联网了
  
请问下卸载了如何安装最新的 需要自己编译吗 releases还是21年的
  
求上面作者发的链接啊 然后点击1published 点击drop下载 https://dev.azure.com/wherewhere/Coolapk-UWP/_build/results?buildId=447&amp;view=artifacts&amp;pathAsName=false&amp;type=publishedArtifacts
  
这个链接是不是失效了 没看到包

**Comment by wherewhere** [comment]
时间过长已经自动清理掉了

**Comment by administrator-WD** [comment]
给我发个8.30的包谢谢，有没有阿里或者百度网盘下载链接

**Comment by Qianchang08** [comment]
通过百度网盘分享的文件：drop.zip
链接:https://pan.baidu.com/s/1Y2dhM3ENYGLit_8eVFQ3Hg&nbsp;
提取码:7p3x
复制这段内容打开「百度网盘APP 即可获取」



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月6日(周四) 晚上7:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Coolapk-UWP/Coolapk-UWP] 网络链接错误 (Issue #149)

**Comment by administrator-WD** [comment]
> 7p3x

谢谢你

**Comment by administrator-WD** [comment]
![image](https://user-images.githubusercontent.com/73874054/194306501-972b3667-60ca-420d-b72d-3399d732fd85.png)
这是什么原因

**Comment by administrator-WD** [comment]
![image](https://user-images.githubusercontent.com/73874054/194306790-edc01854-6025-40f5-ba70-4e1cdca937d3.png)

**Comment by Qianchang08** [comment]
https://www.coolapk.com/feed/39698730?shareKey=NTk5ZDZhOTI1MmRmNjMzZWMyYjU~&amp;shareUid=1879888&amp;shareFrom=com.coolapk.market_12.3.1



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月6日(周四) 晚上7:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Coolapk-UWP/Coolapk-UWP] 网络链接错误 (Issue #149)




 

 这是什么原因

**Comment by administrator-WD** [comment]
> 需要卸载，重新安装，具体看发你的那个链接里的，我也是按照那个解决的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年10月6日(周四) 晚上7:58 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Coolapk-UWP/Coolapk-UWP] 网络链接错误 (Issue #149) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

已解决非常感谢

**Comment by administrator-WD** [comment]
![image](https://user-images.githubusercontent.com/73874054/194339184-21c528c1-aec7-4ee0-a9cc-5e4d4c4e1f2b.png)
现在反复会在一个帖子提示程序错误。

**Comment by Qianchang08** [comment]
不用客气，我只是顺便保存了，希望可以帮助到你！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月6日(周四) 晚上7:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Coolapk-UWP/Coolapk-UWP] 网络链接错误 (Issue #149)




  
7p3x
  
谢谢你

**Comment by WaterSeekingFish** [comment]
啊6

**Comment by UnAptx4869** [comment]
> 不用客气，我只是顺便保存了，希望可以帮助到你！
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年10月6日(周四) 晚上7:52 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Coolapk-UWP/Coolapk-UWP] 网络链接错误 (Issue #149) 7p3x 谢谢你 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

还能在发一下吗 连接失效了

**Comment by BaeKey** [comment]
> > 不用客气，我只是顺便保存了，希望可以帮助到你！
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年10月6日(周四) 晚上7:52 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [Coolapk-UWP/Coolapk-UWP] 网络链接错误 (Issue #149) 7p3x 谢谢你 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 还能在发一下吗 连接失效了

目前最新的链接：https://dev.azure.com/wherewhere/Coolapk-UWP/_build/results?buildId=586&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by 6616H** [comment]
🐂的，牛的，真的解决了

**Comment by BaeKey** [comment]
> l链接失效了，可以再发一下吗？

在这个页面找到最新编译的版本：https://dev.azure.com/wherewhere/Coolapk-UWP/_build
点进去最新的url会有一个版本号，用上面的链接替换一下

当前最新的精简版链接：https://dev.azure.com/wherewhere/Coolapk-UWP/_build/results?buildId=630&view=artifacts&pathAsName=false&type=publishedArtifacts

uwp链接：https://dev.azure.com/wherewhere/Coolapk-UWP/_build/results?buildId=634&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by Aris-Offline** [comment]
![image](https://user-images.githubusercontent.com/65645068/208858653-4e2a5f0d-b2d8-4619-9a77-ef05f070f84d.png)
问题复现了。

**Comment by da1995** [comment]
https://zhuanlan.zhihu.com/p/55906778
无法联网的解决办法，亲测有效

**Comment by SpringAndMay** [comment]
链接失效了，没看到包
