### ISSUE TITLE
网络无法连接,但可以打开登录账号页面

### ISSUE THREAD

**Issue by Administrator6wyj** [Coolapk-UWP/Coolapk-UWP#150]
### Describe the bug

网络无法连接,但可以打开登录账号页面

### Steps to reproduce the bug

直接打开app界面

### Expected behavior

能打开主页

### Screenshots

![image](https://user-images.githubusercontent.com/55020972/187175538-418f78bd-e4e3-4713-9d11-23ed0f291e9b.png)

### App version

2.1.38

### Windows version

Windows 11 version 22H2 (25169)

### Device

Desktop

**Comment by wherewhere** [comment]
#149
