### ISSUE TITLE
程序出现了错误，无法连接到网络

### ISSUE THREAD

**Issue by go0ver** [Coolapk-UWP/Coolapk-UWP#152]
### Describe the bug

![image](https://user-images.githubusercontent.com/44233854/188379126-56538efd-f654-453f-adea-cd587790973c.png)

### Steps to reproduce the bug

只要不点具体内容都正常显示

### App version

2.1.38_test

### Windows version

Windows 11 version 22H2 (22621)

### Device

Desktop

**Comment by NarrowWoodBridge** [comment]
> 

能登陆上账号，但是登陆后因网络错误而看不到任何内容
