### ISSUE TITLE
帖子正常刷新，无法打开

### ISSUE THREAD

**Issue by IapHubery** [Coolapk-UWP/Coolapk-UWP#154]
### Describe the bug

帖子正常刷新，无法打开，提示程序出现了错误

### Steps to reproduce the bug

随便打开一个帖子，打开应用本应显示帖子内容的那一部分黑屏。

### Screenshots

![image](https://user-images.githubusercontent.com/86338252/196181035-7e58a332-a129-4240-9ee3-5cfb2afb8429.png)

![image](https://user-images.githubusercontent.com/86338252/196180662-47b06920-632e-418a-b3a3-ee46bc1285c2.png)

### App version

2.1.39

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### Device

Desktop

**Comment by wherewhere** [comment]
不知道，酷安UWP已停更，建议使用酷安Lite
