### ISSUE TITLE
刷新还是有问题

### ISSUE THREAD

**Issue by 0x00Finch** [Coolapk-UWP/Coolapk-UWP#77]
看截图
![截图_2020-08-13_12,51,18](https://user-images.githubusercontent.com/26269474/90180388-bc5e0300-dd63-11ea-8c9c-629d8a0262b4.png)

**Comment by CodeForCSharp** [comment]
因为作者又改了代码，反正我上次改完是没问题的。有空我再看看发生了什么。

**Comment by hxys-edith** [comment]
在摄影话题里选择按时间排序，然后下拉到该刷新的时候就会跳回顶部，抽风似的

**Comment by wherewhere** [comment]
换坑之后没有这个问题了
